########################################################################
#                               Justfile                               #
#                                                                      #
# Set of routines to execute for project development and management.   #
# Written against `just 1.8.0`.                                        #
########################################################################

default:
	just --list

# Runs the benchmark suite.
bench *ARGS: check
	cargo +nightly bench {{ARGS}}

# Builds the project.
build: check
	cargo build --no-default-features --lib
	cargo build --no-default-features --lib --features alloc
	cargo build        --all-features --lib
	cargo build        --all-features --examples

# Checks the project for syntax and HIR errors.
check:
	cargo clippy --no-default-features
	cargo clippy --no-default-features --features alloc
	cargo clippy        --all-features

# Runs all of the recipes necessary for pre-publish.
checkout: check build doc test package

# Runs the cross-compile battery test.
#
# This is suitable for a development machine **only**, and should not run in CI.
cross: rustup_targets
	@# xargs -n1 -I'{}' env ENABLE_CROSS=1 TARGET='{}' ci/script.sh        --all-features                          < ci/target_test_all.txt
	xargs -n1 -I'{}' env ENABLE_CROSS=1 TARGET='{}' ci/script.sh --no-default-features --features atomic,std    < ci/target_test_no_serde.txt

	xargs -n1 -I'{}' env DISABLE_TESTS=1 TARGET='{}' ci/script.sh        --all-features                         < ci/target_check_all.txt
	xargs -n1 -I'{}' env DISABLE_TESTS=1 TARGET='{}' ci/script.sh --no-default-features --features atomic,std   < ci/target_check_no_serde.txt
	xargs -n1 -I'{}' env DISABLE_TESTS=1 TARGET='{}' ci/script.sh --no-default-features --features atomic,alloc < ci/target_check_no_std.txt

# Runs the cross-compile battery in some parallelism.
#
# This is only useful if don’t expect the tests to fail, because
cross_par: rustup_targets
	@# You will need to run this the first time you start cross-compiling
	@# on a given machine.
	@# TRAVIS_OS_NAME=linux ci/install_rust.sh

	xargs -n1 -P4 -I'{}' env ENABLE_CROSS=1 TARGET='{}' ci/script.sh        --all-features                          < ci/target_test_all.txt
	xargs -n1 -P4 -I'{}' env ENABLE_CROSS=1 TARGET='{}' ci/script.sh --no-default-features --features atomic,std    < ci/target_test_no_serde.txt

	xargs -n1 -P4 -I'{}' env DISABLE_TESTS=1 TARGET='{}' ci/script.sh        --all-features                         < ci/target_check_all.txt
	xargs -n1 -P4 -I'{}' env DISABLE_TESTS=1 TARGET='{}' ci/script.sh --no-default-features --features atomic,std   < ci/target_check_no_serde.txt
	xargs -n1 -P4 -I'{}' env DISABLE_TESTS=1 TARGET='{}' ci/script.sh --no-default-features --features atomic,alloc < ci/target_check_no_std.txt

doc:
	cargo doc --all-features --document-private-items

# Looks for undefined behavior in the (non-doc) test suite.
miri *ARGS:
	cargo +nightly miri test --features atomic,serde,std -q --lib --tests {{ARGS}}

package:
	cargo package --allow-dirty

# Publishes the crate to crates.io
publish: checkout
	cargo publish

# Installs *every* target.
rustup_targets:
	xargs -P1 rustup target add < ci/targets.txt 2>&1 | grep -v "up to date" || true

# Run the test suite.
#
# If arguments are provided, they select both `#[test]` functions and doctests.
test *ARGS: check
	just test_lib {{ARGS}}
	just test_doc
	just test_examples

# Runs the library and integration tests.
test_lib *ARGS:
	cargo test --no-default-features                  -q --lib --tests {{ARGS}}
	cargo test --no-default-features --features alloc -q --lib --tests {{ARGS}}
	cargo test        --all-features                  -q --lib --tests {{ARGS}}

# Runs the doctests.
test_doc *ARGS:
	cargo test        --all-features                  -q --doc         {{ARGS}}

# Runs the example programs (suppressing their output)
test_examples:
	echo aliasing ipv4 sieve tour \
	| xargs -n1 cargo run --all-features --example
